env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - prettier
rules: {
  quotes: ["error", "single"],
  semi: ["error", "never"],
  react/prop-types: "off",
  no-unused-vars: 1,
  no-case-declarations: 0,
  react-hooks/rules-of-hooks: "error",
  react-hooks/exhaustive-deps: "warn",
  prettier/prettier: "warn",
}
